@uri=http://localhost:2918


### Select All - Map
GET {{uri}}/books-map HTTP/1.1


### Search MAP
### keywords -> board{name and author and price ...} or board{name and author and price} ...
### Use and inside board, use or each boards
POST {{uri}}/books-map HTTP/1.1
content-type: application/json

{
    "keywords": [
        {
            "AUTHOR": "Carl Edward Sagan"
        },
        {
            "AUTHOR": "김용"
        },
        {
            "NAME": "흔한남매 7",
            "AUTHOR": "백난도"
        }
    ],
    "options": {
        "page": 0,
        "count": 3
    }
}


### Add book MAP
PUT {{uri}}/books-map HTTP/1.1
content-type: application/json

[
    {
        "NAME": "The Quick and Easy Way to Effective Speaking",
        "PRICE": "10.99",
        "AUTHOR": "Dale Carnegie",
        "ISBN": "9780671724009"
    },
    {
        "NAME": "Beyond Order: 12 More Rules for Life",
        "PRICE": "31.95",
        "AUTHOR": "Jordan B. Peterson",
        "ISBN": "9780593084649"
    },
    {
        "NAME": "흔한남매 7",
        "PRICE": "10800",
        "AUTHOR": "백난도",
        "ISBN": "9791164137527"
    },
    {
        "NAME": "Cosmos",
        "PRICE": "19.05",
        "AUTHOR": "Carl Edward Sagan",
        "ISBN": "9780375508325"
    },
    {
        "NAME": "사조영웅전",
        "PRICE": "65000",
        "AUTHOR": "김용",
        "ISBN": "9788934987475"
    },
    {
        "NAME": "신조협려",
        "PRICE": "102400",
        "AUTHOR": "김용",
        "ISBN": "9788934985808"
    },
    {
        "NAME": "주택과 세금",
        "PRICE": "7000",
        "AUTHOR": "국세청",
        "ISBN": "9791163060390"
    },
    {
        "NAME": "PSPICE for Circuit Theory and Electronic Devices",
        "PRICE": "57000",
        "AUTHOR": "Tobin, Paul",
        "ISBN": "9781598291568"
    }
]

### Edit book
PATCH {{uri}}/book-map HTTP/1.1
content-type: application/json

{
    "IDX": "2",
    "NAME": "aBatman: The Dark Knight Returns",
    "AUTHOR": "Frank Miller",
    "PRICE": "17.33",
    "ISBN": "9781563893421"
}