@uri=http://localhost:2918


### Select one
GET {{uri}}/book/1 HTTP/1.1


### Select All - Limit 10
GET {{uri}}/books HTTP/1.1

### Select All - Map
GET {{uri}}/boards-map HTTP/1.1


### Select Data No paging, no search. listCount of /db/db.go: 3
POST {{uri}}/books HTTP/1.1
content-type: application/json


### Total page
POST {{uri}}/total-page HTTP/1.1
content-type: application/json

{
    "keywords": [],
    "options": {
        "count": 2
    }
}


### Paging - Same as below search except keywords
POST {{uri}}/books HTTP/1.1
content-type: application/json

{
    "keywords": [],
    "options": {
        "page": 0,
        "count": 2,
        "order": "asc"
    }
}


### Search
### keywords -> book{name and author and price ...} or book{name and author and price} ...
### Use and inside book, use or each books
POST {{uri}}/books HTTP/1.1
content-type: application/json

{
    "keywords": [
        {
            "author": "Carl Edward Sagan"
        },
        {
            "author": "김용"
        },
        {
            "name": "흔한남매 7",
            "author": "백난도"
        }
    ],
    "options": {
        "page": 0,
        "count": 3
    }
}

### Search MAP
### keywords -> board{name and author and price ...} or board{name and author and price} ...
### Use and inside board, use or each boards
POST {{uri}}/boards-map HTTP/1.1
content-type: application/json

{
    "keywords": [
        {
            "author": "Carl Edward Sagan"
        },
        {
            "author": "김용"
        },
        {
            "name": "흔한남매 7",
            "author": "백난도"
        }
    ],
    "options": {
        "page": 0,
        "count": 3
    }
}

### Add book #1
PUT {{uri}}/books HTTP/1.1
content-type: application/json

[
    {
        "name": "The Quick and Easy Way to Effective Speaking",
        "price": "10.99",
        "author": "Dale Carnegie",
        "isbn": "9780671724009"
    },
    {
        "name": "Beyond Order: 12 More Rules for Life",
        "price": "31.95",
        "author": "Jordan B. Peterson",
        "isbn": "9780593084649"
    },
    {
        "name": "흔한남매 7",
        "price": "10800",
        "author": "백난도",
        "isbn": "9791164137527"
    },
    {
        "name": "Cosmos",
        "price": "19.05",
        "author": "Carl Edward Sagan",
        "isbn": "9780375508325"
    },
    {
        "name": "사조영웅전",
        "price": "65000",
        "author": "김용",
        "isbn": "9788934987475"
    },
    {
        "name": "신조협려",
        "price": "102400",
        "author": "김용",
        "isbn": "9788934985808"
    },
    {
        "name": "주택과 세금",
        "price": "7000",
        "author": "국세청",
        "isbn": "9791163060390"
    },
    {
        "name": "PSPICE for Circuit Theory and Electronic Devices",
        "price": "57000",
        "author": "Tobin, Paul",
        "isbn": "9781598291568"
    }
]

### Add book #2 - Insert error - Duplicate ISBN
PUT {{uri}}/books HTTP/1.1
content-type: application/json

[
    {
        "name": "흔한남매 7",
        "price": "10800",
        "author": "백난도",
        "isbn": "9791164137527"
    }
]

### Edit book
PATCH {{uri}}/book HTTP/1.1
content-type: application/json

{
    "idx": "2",
    "name": "Batman: The Dark Knight Returns",
    "author": "Frank Miller",
    "price": "17.33",
    "isbn": "9781563893421"
}

### DELETE book
DELETE {{uri}}/book/6 HTTP/1.1
