@uri=http://localhost:2918



### Select one
GET {{uri}}/book/1 HTTP/1.1


### Select All - Limit 10
GET {{uri}}/books HTTP/1.1


### Select Data No paging, no search. listCount of /db/db.go: 3
POST {{uri}}/books HTTP/1.1
content-type: application/json


### Total page
POST {{uri}}/total-page HTTP/1.1
content-type: application/json

{
    "keywords": [],
    "options": {
        "count": 2
    }
}


### Paging - 아래 Search에서 keyword만 제외
POST {{uri}}/books HTTP/1.1
content-type: application/json

{
    "keywords": [],
    "options": {
        "page": 0,
        "count": 2,
        "order": "asc"
    }
}


### Search
### keywords -> book{name and author and price ...} or book{name and author and price} ...
### book 내부는 and, book끼리는 or
POST {{uri}}/books HTTP/1.1
content-type: application/json

{
    "keywords": [
        {
            "author": "칼 세이건"
        },
        {
            "author": "김용"
        },
        {
            "name": "흔한남매 7",
            "author": "백난도"
        }
    ],
    "options": {
        "page": 0,
        "count": 3
    }
}

### Add book #1
PUT {{uri}}/books HTTP/1.1
content-type: application/json

[
    {
        "name": "데일 카네기 인간관계론",
        "price": "13000",
        "author": "데일 카네기",
        "isbn": "9788975070624"
    },
    {
        "name": "질서 너머",
        "price": "17800",
        "author": "조던 피터슨",
        "isbn": "9788901249599"
    },
    {
        "name": "흔한남매 7",
        "price": "10800",
        "author": "백난도",
        "isbn": "9791164137527"
    },
    {
        "name": "코스모스",
        "price": "16650",
        "author": "칼 세이건",
        "isbn": "9788983711892"
    },
    {
        "name": "사조영웅전",
        "price": "65000",
        "author": "김용",
        "isbn": "9788934987475"
    },
    {
        "name": "신조협려",
        "price": "102400",
        "author": "김용",
        "isbn": "9788934985808"
    },
    {
        "name": "주택과 세금",
        "price": "7000",
        "author": "국세청",
        "isbn": "9791163060390"
    },
    {
        "name": "PSPICE for Circuit Theory and Electronic Devices",
        "price": "57000",
        "author": "Tobin, Paul",
        "isbn": "9781598291568"
    }
]

### Add book #2 - Insert error - Duplicate ISBN
PUT {{uri}}/books HTTP/1.1
content-type: application/json

[
    {
        "name": "흔한남매 7",
        "price": "10800",
        "author": "백난도",
        "isbn": "9791164137527"
    }
]

### Edit book
PATCH {{uri}}/book HTTP/1.1
content-type: application/json

{
    "idx": "2",
    "name": "배트맨 다크 나이트 리턴즈 1",
    "author": "프랭크 밀러",
    "price": "15000",
    "isbn": "9788983713971"
}

### DELETE book
DELETE {{uri}}/book/6 HTTP/1.1
